// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $examples_id_ from "./routes/examples/[id].ts";
import * as $index from "./routes/index.tsx";
import * as $meta from "./routes/meta.ts";
import * as $playgrounds_id_ from "./routes/playgrounds/[id].tsx";
import * as $playgrounds_index from "./routes/playgrounds/index.ts";
import * as $playground_playground_island from "./islands/playground/playground_island.tsx";
import * as $playground_playground_script from "./islands/playground/playground_script.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/examples/[id].ts": $examples_id_,
    "./routes/index.tsx": $index,
    "./routes/meta.ts": $meta,
    "./routes/playgrounds/[id].tsx": $playgrounds_id_,
    "./routes/playgrounds/index.ts": $playgrounds_index,
  },
  islands: {
    "./islands/playground/playground_island.tsx": $playground_playground_island,
    "./islands/playground/playground_script.tsx": $playground_playground_script,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
