// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $meta from "./routes/meta.ts";
import * as $playgrounds_id_ from "./routes/playgrounds/[id].ts";
import * as $playgrounds_index from "./routes/playgrounds/index.ts";
import * as $playground_build from "./islands/playground/build.ts";
import * as $playground_deps from "./islands/playground/deps.ts";
import * as $playground_editor from "./islands/playground/editor.ts";
import * as $playground_elements from "./islands/playground/elements.ts";
import * as $playground_output from "./islands/playground/output.ts";
import * as $playground_playground from "./islands/playground/playground.ts";
import * as $playground_playground_island from "./islands/playground/playground_island.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/meta.ts": $meta,
    "./routes/playgrounds/[id].ts": $playgrounds_id_,
    "./routes/playgrounds/index.ts": $playgrounds_index,
  },
  islands: {
    "./islands/playground/build.ts": $playground_build,
    "./islands/playground/deps.ts": $playground_deps,
    "./islands/playground/editor.ts": $playground_editor,
    "./islands/playground/elements.ts": $playground_elements,
    "./islands/playground/output.ts": $playground_output,
    "./islands/playground/playground.ts": $playground_playground,
    "./islands/playground/playground_island.tsx": $playground_playground_island,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
